id: P006923
initial_creation_type: ocr
source_metadata:
  id: bdr:W1KG24061
  title: བློ་བཟང་དགོངས་རྒྱན་མུ་ཏིག་ཕྲེང་མཛེས་དེབ་ཞེ་བཞི་པ།
  author: ''
  volumes:
    fa44917661344f609cbd4868821bc057:
      image_group_id: I1KG24227
      title: ''
      volume_number: 1
      total_pages: 266
      base_file: v001.txt
