id: P006923
initial_creation_type: ocr
created_at: 28/03/2020
last_modified_at: 2021-12-17 12:30:58.439125
source_metadata:
  id: bdr:W1KG24061
  title: བློ་བཟང་དགོངས་རྒྱན་མུ་ཏིག་ཕྲེང་མཛེས་དེབ་ཞེ་བཞི་པ།
  author: ''
  volumes:
    fa44917661344f609cbd4868821bc057:
      image_group_id: I1KG24227
      title: ''
      volume_number: 1
      total_pages: 266
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
