id: I466CDCC6
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-28T20:26:19+00:00'
last_modified: '2022-06-08T12:30:59.744554+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG24061
  title: བློ་བཟང་དགོངས་རྒྱན་མུ་ཏིག་ཕྲེང་མཛེས་དེབ་ཞེ་བཞི་པ།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
  base:
    676E:
      image_group_id: I1KG24227
      title: ''
      total_pages: 266
      order: 1
      base_file: 676E.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
